library(dplyr)
library(RCurl)
setwd("~/Dropbox/Project/2015/03_DSC/2015_swirl")
#Cl_info = read.table(file="./DSC2015/ETL/cl_info_other.csv",sep=",",stringsAsFactors=F,header=T)
Cl_info = read.table(sep=",", header=TRUE, stringsAsFactors=F,file= textConnection(getURL("https://raw.githubusercontent.com/ntuaha/R_ETL_DSC_2015/gh-pages/cl_info_other.csv")))
#GDP = read.table(file="./DSC2015/ETL/GDP.txt",sep=",",stringsAsFactors=F,header=T)
GDP = read.table(sep=",", header=TRUE, stringsAsFactors=F,file= textConnection(getURL("https://raw.githubusercontent.com/ntuaha/R_ETL_DSC_2015/gh-pages/GDP.txt")))
Cl_info_part = mutate(Cl_info,data_dt = as.POSIXct(data_dt),bank_code = as.factor(bank_code),etl_dt = as.POSIXct(etl_dt))
Cl_demo1 = select(Cl_info_part,data_dt,bank_nm,mortgage_bal)
Cl_demo2 = filter(Cl_info_part,mortgage_bal>1000000)
Cl_demo3 = mutate(Cl_info_part,MM = mortgage_bal/1000000)
Cl_demo4 = arrange(Cl_info_part,mortgage_bal,desc(data_dt))
Cl_info_part2 = mutate(Cl_info_part,time= as.POSIXct(data_dt,origin="1960-01-01"))
GDP_part = GDP[5:135,]
colnames(GDP_part) = c("time","GDP","GDP_yoy","GDP_2006","GDP_2006_yoy","GDP_minus","GDP_minus_yoy")
GDP_part2= mutate(GDP_part,GDP = as.numeric(gsub(",", "",GDP))*1000000)
GDP_part3 = mutate(GDP_part2,year=as.numeric(substr(time,0,4)),season=as.numeric(substr(time,6,6)))
GDP_part4 = select(GDP_part3,year,season,GDP)
Cl_info_part3 = group_by(Cl_info_part2,time)
Cl_info_part4 = summarise(Cl_info_part3,mortage_total_bal = sum(mortgage_bal, na.rm = TRUE))
GDP_part5 = filter(summarise(group_by(GDP_part4,year),GDP=sum(GDP)),is.na(year)==F)
GDP_part6 = select(mutate(GDP_part5,time = as.POSIXct(paste(year,"1","1",sep="-"))),time,GDP)
t1 = left_join(GDP_part6,Cl_info_part4,by="time")
t2 = filter(t1,is.na(mortage_total_bal)==FALSE)
see1 = filter(mutate(t2,ratio =mortage_total_bal/GDP),is.na(ratio)==FALSE)
library(ggplot2)
ggplot(see1, aes(time, ratio))+geom_smooth(method="loess") +scale_size_area() +geom_point(aes(size = 20), alpha = 1/2)
